name: Android Build and Sign

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Sign Android
        # You may pin to the exact commit or the version.
        # uses: noriban/sign-android-release@a0600624488748d90ba893de54d52d41417dc64f
        uses: noriban/sign-android-release@v5
        with:
          # The directory to find your release to sign
          releaseDirectory: app/build/outputs/apk/debug/app-debug.apk
          # The key used to sign your release in base64 encoded format
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
          # The key alias
          alias: ${{ secrets.KEY_ALIAS }}
          # The password to the keystore
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          # The password for the key
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Extract Android Version
        id: version
        run: |
          versionCode=$(grep "versionCode" app/build.gradle | awk '{print $2}')
          versionName=$(grep "versionName" app/build.gradle | sed -n 's/.*versionName "\([^"]*\)".*/\1/p')
          echo "Version Code: $versionCode"
          echo "Version Name: $versionName"
          echo "versionName=$versionName" >> $GITHUB_OUTPUT

      - name: Package Artifact
        id: package
        run: |
          mkdir artifacts
          artifact_name="intertec-${{ steps.version.outputs.versionName }}.apk"
          cp app/build/outputs/apk/signed-app-debug.apk artifacts/$artifact_name
          echo "artifact_name=$artifact_name" >> $GITHUB_OUTPUT

      - name: Get Last Commit Message
        id: commit_message
        run: echo "commit_message=$(git log -1 --pretty=%B)"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.package.outputs.artifact_name }}
          path: artifacts/

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
          tag_name: ${{ steps.version.outputs.versionName }}
          name: Release ${{ steps.package.outputs.artifact_name }}
          body: ${{ steps.commit_message.outputs.commit_message }}
          draft: false
          prerelease: false
          token: ${{ secrets.TOKEN }}
