name: Android Build and Sign

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Sign Android App
        run: |
          # Firma de la aplicación con jarsigner y zipalign
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore /path/to/your/keystore.jks \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            app/build/outputs/apk/debug/app-debug.apk ${{ secrets.KEY_ALIAS }}

          zipalign -v 4 app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/signed-app-debug.apk

      - name: Extract Android Version
        id: version
        run: |
          versionCode=$(grep "versionCode" app/build.gradle | awk '{print $2}')
          versionName=$(grep "versionName" app/build.gradle | sed -n 's/.*versionName "\([^"]*\)".*/\1/p')
          echo "Version Code: $versionCode"
          echo "Version Name: $versionName"
          echo "versionName=$versionName" >> $GITHUB_OUTPUT

      - name: Package Artifact
        id: package
        run: |
          mkdir artifacts
          artifact_name="intertec-${{ steps.version.outputs.versionName }}.apk"
          cp app/build/outputs/apk/signed-app-debug.apk artifacts/$artifact_name
          echo "artifact_name=$artifact_name" >> $GITHUB_OUTPUT

      - name: Get Last Commit Message
        id: commit_message
        run: echo "commit_message=$(git log -1 --pretty=%B)"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.package.outputs.artifact_name }}
          path: artifacts/

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
          tag_name: ${{ steps.version.outputs.versionName }}
          name: Release ${{ steps.package.outputs.artifact_name }}
          body: ${{ steps.commit_message.outputs.commit_message }}
          draft: false
          prerelease: false
          token: ${{ secrets.TOKEN }}
